### ISSUE TITLE
Cannot read property 'getContext' of undefined

### ISSUE THREAD

**Issue by psanders** [tourjs/tour#2]
First of all thanks for sharing TourJS, I think people are going to love.

I'm trying to run a simple tour but I'm getting the exception: _Uncaught TypeError: Cannot read property 'getContext' of undefined._

What could that be?

Here is what I'm doing [TourJS-test](https://gist.github.com/psanders/64e23d64a06bf87dcde86adc76908b17)

**Comment by psanders** [comment]
Nevermind. I needed to wait for the page to be ready before calling start...

**Comment by tannerlinsley** [comment]
Thanks! Glad you solved it!

**Comment by Hypercubed** [comment]
Actually, this is still and issue in an angular app.  The init() function may be called after the DOMContentLoaded event.  The issue can be worked around by adding a init function to the service:

```js
const service = {
  current: null,
  //
  start,
  stop,
  next,
  previous,
  goto,
  init() {
    injectTemplate()
    resolveEventSystem()
  }
}
```

**Comment by tannerlinsley** [comment]
So you think it would be sufficient to call the unit function in the dom
ready callback?

**Comment by tannerlinsley** [comment]
Init *

**Comment by Hypercubed** [comment]
Actually, now I'm not sure if it is due to the angular or SystemJS environment.  But the `DOMContentLoaded`/dome ready callbacks are fired before the tour.js script is loaded.  So in this setup, we need a way to call `init` manually in the controller.  Exposing the `init` works in my case.

**Comment by tannerlinsley** [comment]
My proposal is that we automatically fire the init on first tour run. Its
almost instantaneous, and it will feel like less setup to most people (even
though its would technically be trivial to do manually)

**Comment by Hypercubed** [comment]
That sounds fine as well.
