### ISSUE TITLE
Import package on angularjs + webpack 1

### ISSUE THREAD

**Issue by jonasschumacher** [tourjs/tour#20]
Hi there!

I couldn't import it using angularjs + webpack 1.

I've tried many ways:

```
import 'tour';
import Tour from 'tour';
import { default as Tour } from 'tour';
....
```
Also tried adding it to webpack plugins:

```
  new webpack.ProvidePlugin({
      jQuery: 'jquery',
      Tour  : 'tour'
    }),

```
Can anybody help me?

**Comment by davidnagli** [comment]
Hi 🙂 

Not really sure why it's giving you those issues (maybe paste in the errors and I can try to assist 🚀)

**Comment by jonasschumacher** [comment]
Thanks for your fast reply.
After some more research I could make it run through angularjs constants:
First:
`import Tour from 'tour';`

And then:
```
angular()
  .module()
  .constant('Tour', Tour);
```
I guess it was just my lack of knoledge with angulajs. I'm sorry for bothering.

**Comment by davidnagli** [comment]
No worries! Glad you got it figured out.
