### ISSUE TITLE
Mixed esm and cjs causes issues in some environments

### ISSUE THREAD

**Issue by Hypercubed** [tourjs/tour#5]
The `tour.js` file contains both ESM imports (https://github.com/tourjs/tour/blob/master/src/tour.js#L1) and CJS `module.exports` (https://github.com/tourjs/tour/blob/master/src/tour.js#L62).  This is causing JSPM to identify this file as a CJS file, and therefore skip transpile.  One can override the install to force ESM, however, this will error on the `module.exports`.

I suggest line 62 should read: 

```js
export default service
```

**Comment by tannerlinsley** [comment]
That would be great, but then the standalone window.Tour property would =
{default: service}, right?

**Comment by Hypercubed** [comment]
Yes, that has been an issue with mixed modules for a while.  You might need to make a shim.  Something like:

```js
modules.exports = require('./src/tour.js').default;
```

**Comment by tannerlinsley** [comment]
Should be fixed in latest publish (2.0.2 (funny story on that semver tag there)). Confirm?

**Comment by tannerlinsley** [comment]
I've confirmed this.  Everything is in esm format now, and I've updated the readme for commonjs/vanilla installation

**Comment by Hypercubed** [comment]
Yes!   Works great.  To install in jspm I still needed to force esm using `jspm install npm:tour -o "{ format: 'esm' }"` but that's typical.

**Comment by tannerlinsley** [comment]
Yeah not too worried. Jspm is still up and coming. I'm sure we'll keep an
eye on this one as things change.
